// VueJs/authentications/src/App.vue
<script setup>
import Navbar from "./components/Navbar.vue";
</script>

<template>
  <div class="flex flex-col min-h-screen">
    <!-- Top Navbar -->
    <Navbar />

    <!-- Main Content -->
    <main class="flex-1 p-4 bg-gray-50">
      <router-view />
    </main>

    <!-- Footer -->
    <footer class="p-4 text-center text-gray-500 bg-gray-200">
      © 2025 My Vue App
    </footer>
  </div>
</template>

// React/Redux/crud-redux/src/App.jsx
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import CreateEmployee from "./Pages/CreateEmployee";
import GetEmployee from "./Pages/GetEmployee";
import EditEmployee from "./Pages/EditEmployee";
import ViewEmployee from "./Pages/ViewEmployee";

function App() {
  return (
    <Router>
      <div className="flex flex-col min-h-screen">
        <Navbar />

        <main className="flex-grow">
          <Routes>
            {/* <Route path="/" element={<Form />} /> */}
            <Route path="/" element={<GetEmployee />} />
            <Route path="/create" element={<CreateEmployee />} />
            <Route path="/edit/:id" element={<EditEmployee />} />
            <Route path="/view/:id" element={<ViewEmployee />} />
            <Route
              path="/about"
              element={<div className="p-6">About Page</div>}
            />
            <Route
              path="/contact"
              element={<div className="p-6">Contact Page</div>}
            />
          </Routes>
        </main>

        {/* Footer stays at bottom */}
        <Footer />
      </div>
    </Router>
  );
}

export default App;
